apiVersion: v1
kind: Secret
metadata:
  name: googoo-db-credentials
  namespace: googoo-platform
type: Opaque
stringData:
  POSTGRES_DB: uber_clone
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: example
